services:
  mcp-server:
    container_name: mcp-tutorial-server
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
